version: '3.8'

volumes:
  swe-data:
    name: swe-data
  swe-secrets:
    name: swe-secrets

services:
  swe:
    image: agentscope/swe:latest
    container_name: swe
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - SWE_AUTH_ENABLED=true
    #   - SWE_AUTH_USERNAME=admin
    #   - SWE_AUTH_PASSWORD=yourpassword
    volumes:
      - swe-data:/app/working
      - swe-secrets:/app/working.secret